-- +goose Up
CREATE TABLE users (
    id UUID PRIMARY KEY, -- Generated by the application (UUID v7 preferred)
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    full_name TEXT NOT NULL CHECK (full_name <> ''),
    avatar_url TEXT,
    phone_number TEXT, -- E.164 format (e.g. +14155552671)
    country_code CHAR(2) CHECK (LENGTH(country_code) = 2), -- ISO 3166-1 alpha-2 (e.g. US, DE)
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- We store the SHA256 hash of the refresh token, not the token itself
CREATE TABLE refresh_tokens (
    token_hash BYTEA PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_agent TEXT,
    ip_address TEXT
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);

-- +goose Down
DROP TABLE refresh_tokens;
DROP TABLE users;

